//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokedex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pokeInfo
    {
        public int id { get; set; }
        public string num { get; set; }
        public string cName { get; set; }
        public string jName { get; set; }
        public string eName { get; set; }
        public string typeA { get; set; }
        public string typeB { get; set; }
        public string pokeGroup { get; set; }
        public string abilityA { get; set; }
        public string abilityB { get; set; }
        public string hideAbility { get; set; }
        public string h { get; set; }
        public string w { get; set; }
        public string gender { get; set; }
        public string hp { get; set; }
        public string attack { get; set; }
        public string defens { get; set; }
        public string sAttack { get; set; }
        public string sDefencs { get; set; }
        public string speed { get; set; }
        public string describe { get; set; }
        public string creator { get; set; }
    }
}
